'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import React from 'react';
import { Provider } from 'react-redux';
import store from './redux/store';
import styled from 'styled-components';



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// Styled component
const AppContainer = styled.div`
  max-width: 800px;
  margin: 0 auto;
`;

// Redux store

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang='en'>
       <head>
      </head>
      <body>
        <Provider store={store}>
          <AppContainer>
            {children}
          </AppContainer>
        </Provider>
      </body>
    </html>
 
  )
}
